import { ref } from 'vue'

export const allCards = ref([
  {
    cardName: 'Le Mat',
    modality: 'Cardinal',
    element: 'Fire',
    planet: '',
    sign: '',
  },
  {
    cardName: 'Chariot',
    modality: 'Fixed',
    element: 'Air',
    planet: '',
    sign: '',
  },
  {
    cardName: 'Wheel',
    modality: 'Mutable',
    element: 'Water',
    planet: '',
    sign: '',
  },
  {
    cardName: 'Sun',
    modality: '',
    element: '',
    planet: 'Sol',
    sign: 'Leo',
  },
  {
    cardName: 'Moon',
    modality: '',
    element: '',
    planet: 'Luna',
    sign: 'Cancer',
  },
  {
    cardName: 'Hanged Man',
    modality: '',
    element: '',
    planet: 'Mercury',
    sign: 'Virgo, Gemini',
  },
  {
    cardName: 'Lovers',
    modality: '',
    element: '',
    planet: 'Venus',
    sign: 'Libra, Taurus',
  },
  {
    cardName: 'Tower',
    modality: '',
    element: '',
    planet: 'Mars',
    sign: 'Aries, Scorpio',
  },
  {
    cardName: 'Justice',
    modality: '',
    element: '',
    planet: 'Jupiter',
    sign: 'Pisces, Sagittarius',
  },
  {
    cardName: 'Death',
    modality: '',
    element: 'Earth',
    planet: 'Saturn',
    sign: 'Aquarius, Capricorn',
  },
  {
    cardName: 'Emperor',
    modality: 'Cardinal',
    element: 'Fire',
    planet: 'Mars',
    sign: 'Aries',
  },
  {
    cardName: 'Empress',
    modality: 'Cardinal',
    element: 'Air',
    planet: 'Venus',
    sign: 'Libra',
  },
  {
    cardName: 'Devil',
    modality: 'Fixed',
    element: 'Earth',
    planet: 'Venus',
    sign: 'Taurus',
  },
  {
    cardName: 'Star',
    modality: 'Fixed',
    element: 'Fire',
    planet: 'Sol',
    sign: 'Leo',
  },
  {
    cardName: 'Mountebank',
    modality: 'Mutable',
    element: 'Air',
    planet: 'Mercury',
    sign: 'Gemini',
  },
  {
    cardName: 'Popess',
    modality: 'Cardinal',
    element: 'Water',
    planet: 'Luna',
    sign: 'Cancer',
  },
  {
    cardName: 'Pope',
    modality: 'Cardinal',
    element: 'Earth',
    planet: 'Saturn',
    sign: 'Capricorn',
  },
  {
    cardName: 'Temperance',
    modality: 'Mutable',
    element: 'Earth',
    planet: 'Mercury',
    sign: 'Virgo',
  },
  {
    cardName: 'Hermit',
    modality: 'Fixed',
    element: 'Water',
    planet: 'Mars',
    sign: 'Scorpio',
  },
  {
    cardName: 'World',
    modality: 'Fixed',
    element: 'Air',
    planet: 'Saturn',
    sign: 'Aquarius',
  },
  {
    cardName: 'Judgement',
    modality: 'Mutable',
    element: 'Water',
    planet: 'Jupiter',
    sign: 'Pisces',
  },
  {
    cardName: 'Force',
    modality: 'Mutable',
    element: 'Fire',
    planet: 'Jupiter',
    sign: 'Sagittarius',
  },
])
